VEC_HEADERS := \
    vec/vec.h \
    vec/qc.h  \

VEC_SRC := \
    vec/append.c         \
    vec/as_mut_slice.c   \
    vec/as_slice.c       \
    vec/cap.c            \
    vec/elem.c           \
    vec/filter.c         \
    vec/find.c           \
    vec/foreach.c        \
    vec/foreach_range.c  \
    vec/free.c           \
    vec/free_range.c     \
    vec/from_raw_parts.c \
    vec/get_nth.c        \
    vec/insert.c         \
    vec/is_empty.c       \
    vec/iter.c           \
    vec/iter_end.c       \
    vec/iter_idx.c       \
    vec/iter_next.c      \
    vec/iter_rev.c       \
    vec/itering.c        \
    vec/len.c            \
    vec/map.c            \
    vec/map_range.c      \
    vec/pop.c            \
    vec/push.c           \
    vec/qc.c             \
    vec/qsort.c          \
    vec/remove.c         \
    vec/reserve.c        \
    vec/set_len.c        \
    vec/set_nth.c        \
    vec/shrink_to_fit.c  \
    vec/split_off.c      \
    vec/swap_remove.c    \
    vec/truncate.c       \
    vec/vec.c            \
    vec/with_cap.c       \
