VEC_SRC := \
    vec/append.c        \
    vec/as_mut_slice.c  \
    vec/elem.c          \
    vec/filter.c        \
    vec/find.c          \
    vec/foreach.c       \
    vec/foreach_range.c \
    vec/get_nth.c       \
    vec/insert.c        \
    vec/is_empty.c      \
    vec/iter.c          \
    vec/iter_end.c      \
    vec/iter_next.c     \
    vec/iter_rev.c      \
    vec/itering.c       \
    vec/pop.c           \
    vec/push.c          \
    vec/qc.c            \
    vec/remove.c        \
    vec/swap_remove.c   \
    vec/vec.c           \
